version: "3.8"

services:
  app:
    build: .
    command: ["sh", "-c", "/start.sh"]
    ports:
      - "80:8000"
    env_file:
      - .env
    depends_on:
      - postgres_prod_db

  postgres_prod_db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data


volumes:
  postgres_prod_data:
